cg_assign_velocity.o: cg_assign_velocity.fpp cg_domain_str_mod.mod cg_dynvars_mod.mod cg_dynamics_str_mod.mod
cg_assign_velocity_mod.mod: cg_assign_velocity.fpp cg_assign_velocity.o
cg_boundary.o: cg_boundary.fpp cg_boundary_str_mod.mod cg_enefunc_str_mod.mod cg_ensemble_str_mod.mod cg_energy_mod.mod
cg_boundary_mod.mod: cg_boundary.fpp cg_boundary.o
cg_boundary_str.o: cg_boundary_str.fpp  
cg_boundary_str_mod.mod: cg_boundary_str.fpp cg_boundary_str.o
cg_communicate.o: cg_communicate.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod cg_boundary_str_mod.mod cg_communicate_str_mod.mod
cg_communicate_mod.mod: cg_communicate.fpp cg_communicate.o
cg_communicate_str.o: cg_communicate_str.fpp 
cg_communicate_str_mod.mod: cg_communicate_str.fpp cg_communicate_str.o
cg_constraints.o: cg_constraints.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod cg_constraints_str_mod.mod 
cg_constraints_mod.mod: cg_constraints.fpp cg_constraints.o
cg_constraints_str.o: cg_constraints_str.fpp  
cg_constraints_str_mod.mod: cg_constraints_str.fpp cg_constraints_str.o
cg_control.o: cg_control.fpp cg_input_mod.mod cg_output_mod.mod cg_remd_mod.mod cg_dynamics_mod.mod cg_ensemble_mod.mod cg_rpath_mod.mod cg_minimize_mod.mod cg_energy_mod.mod cg_restraints_mod.mod cg_boundary_mod.mod 
cg_control_mod.mod: cg_control.fpp cg_control.o
cg_domain.o: cg_domain.fpp cg_enefunc_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_domain_str_mod.mod cg_ensemble_str_mod.mod cg_dynvars_str_mod.mod cg_pairlist_str_mod.mod cg_energy_mod.mod cg_boundary_mod.mod 
cg_domain_mod.mod: cg_domain.fpp cg_domain.o
cg_domain_str.o: cg_domain_str.fpp  
cg_domain_str_mod.mod: cg_domain_str.fpp cg_domain_str.o
cg_dynamics.o: cg_dynamics.fpp cg_output_mod.mod cg_domain_str_mod.mod cg_md_leapfrog_mod.mod cg_restraints_str_mod.mod cg_enefunc_str_mod.mod cg_md_vverlet_mod.mod cg_boundary_mod.mod cg_output_str_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_ensemble_str_mod.mod cg_dynvars_str_mod.mod cg_pairlist_str_mod.mod cg_dynamics_str_mod.mod cg_restraints_mod.mod 
cg_dynamics_mod.mod: cg_dynamics.fpp cg_dynamics.o
cg_dynamics_str.o: cg_dynamics_str.fpp  
cg_dynamics_str_mod.mod: cg_dynamics_str.fpp cg_dynamics_str.o
cgdyn.o: cgdyn.fpp cg_domain_str_mod.mod cg_remd_mod.mod cg_md_leapfrog_mod.mod cg_control_mod.mod cg_setup_mpi_mod.mod cg_enefunc_str_mod.mod cg_setup_cgdyn_mod.mod cg_minimize_str_mod.mod cg_minimize_mod.mod cg_md_vverlet_mod.mod cg_dynamics_mod.mod cg_output_str_mod.mod cg_rpath_mod.mod cg_rpath_str_mod.mod cg_remd_str_mod.mod cg_energy_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_ensemble_str_mod.mod cg_dynvars_str_mod.mod cg_pairlist_str_mod.mod cg_dynamics_str_mod.mod 
cg_dynvars.o: cg_dynvars.fpp cg_enefunc_str_mod.mod cg_boundary_str_mod.mod cg_domain_str_mod.mod cg_output_str_mod.mod cg_ensemble_str_mod.mod cg_dynvars_str_mod.mod cg_dynamics_str_mod.mod 
cg_dynvars_mod.mod: cg_dynvars.fpp cg_dynvars.o
cg_dynvars_str.o: cg_dynvars_str.fpp cg_energy_str_mod.mod 
cg_dynvars_str_mod.mod: cg_dynvars_str.fpp cg_dynvars_str.o
cg_enefunc_fit.o: cg_enefunc_fit.fpp cg_enefunc_str_mod.mod cg_restraints_str_mod.mod cg_domain_str_mod.mod 
cg_enefunc_fit_mod.mod: cg_enefunc_fit.fpp cg_enefunc_fit.o
cg_enefunc.o: cg_enefunc.fpp cg_enefunc_str_mod.mod cg_restraints_str_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_domain_str_mod.mod cg_migration_mod.mod cg_energy_str_mod.mod cg_enefunc_localres_mod.mod cg_enefunc_gromacs_mod.mod cg_energy_mod.mod 
cg_enefunc_mod.mod: cg_enefunc.fpp cg_enefunc.o
cg_enefunc_gromacs.o: cg_enefunc_gromacs.fpp cg_enefunc_str_mod.mod cg_restraints_str_mod.mod cg_domain_str_mod.mod cg_communicate_mod.mod cg_enefunc_restraints_mod.mod cg_energy_mod.mod cg_energy_str_mod.mod 
cg_enefunc_gromacs_mod.mod: cg_enefunc_gromacs.fpp cg_enefunc_gromacs.o
cg_enefunc_localres.o: cg_enefunc_localres.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod 
cg_enefunc_localres_mod.mod: cg_enefunc_localres.fpp cg_enefunc_localres.o
cg_enefunc_restraints.o: cg_enefunc_restraints.fpp cg_enefunc_str_mod.mod cg_restraints_str_mod.mod cg_domain_str_mod.mod 
cg_enefunc_restraints_mod.mod: cg_enefunc_restraints.fpp cg_enefunc_restraints.o
cg_enefunc_str.o: cg_enefunc_str.fpp cg_domain_str_mod.mod 
cg_enefunc_str_mod.mod: cg_enefunc_str.fpp cg_enefunc_str.o
cg_energy_angles.o: cg_energy_angles.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod 
cg_energy_angles_mod.mod: cg_energy_angles.fpp cg_energy_angles.o
cg_energy_bases.o: cg_energy_bases.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod 
cg_energy_bases_mod.mod: cg_energy_bases.fpp cg_energy_bases.o
cg_energy_bonds.o: cg_energy_bonds.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod 
cg_energy_bonds_mod.mod: cg_energy_bonds.fpp cg_energy_bonds.o
cg_energy_dihedrals1.o: cg_energy_dihedrals.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod 
cg_energy_dihedrals_mod.mod: cg_energy_dihedrals.fpp cg_energy_dihedrals.o
cg_energy_dihedrals.o: cg_energy_dihedrals.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod 
cg_energy_dihedrals_mod.mod: cg_energy_dihedrals.fpp cg_energy_dihedrals.o
cg_energy.o: cg_energy.fpp cg_energy_restraints_mod.mod cg_domain_str_mod.mod cg_energy_nonlocal_mod.mod cg_energy_martini_mod.mod cg_restraints_str_mod.mod cg_enefunc_str_mod.mod cg_dynvars_str_mod.mod cg_energy_bonds_mod.mod cg_energy_dihedrals_mod.mod cg_energy_go_mod.mod cg_energy_bases_mod.mod cg_energy_str_mod.mod cg_boundary_str_mod.mod cg_pairlist_str_mod.mod cg_energy_angles_mod.mod cg_energy_martini_mod.mod
cg_energy_mod.mod: cg_energy.fpp cg_energy.o
cg_energy_go.o: cg_energy_go.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod cg_pairlist_str_mod.mod 
cg_energy_go_mod.mod: cg_energy_go.fpp cg_energy_go.o
cg_energy_nonlocal.o: cg_energy_nonlocal.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod cg_pairlist_str_mod.mod 
cg_energy_nonlocal_mod.mod: cg_energy_nonlocal.fpp cg_energy_nonlocal.o
cg_energy_martini.o: cg_energy_martini.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod cg_pairlist_str_mod.mod 
cg_energy_martini_mod.mod: cg_energy_martini.fpp cg_energy_martini.o
cg_energy_restraints.o: cg_energy_restraints.fpp cg_enefunc_str_mod.mod cg_restraints_str_mod.mod cg_domain_str_mod.mod cg_boundary_str_mod.mod cg_rpath_str_mod.mod cg_enefunc_fit_mod.mod 
cg_energy_restraints_mod.mod: cg_energy_restraints.fpp cg_energy_restraints.o
cg_energy_str.o: cg_energy_str.fpp  
cg_energy_str_mod.mod: cg_energy_str.fpp cg_energy_str.o
cg_energy_table_linear_bondcorr.o: cg_energy_table_linear_bondcorr.fpp cg_pairlist_str_mod.mod cg_enefunc_str_mod.mod cg_domain_str_mod.mod 
cg_energy_table_linear_bondcorr_mod.mod: cg_energy_table_linear_bondcorr.fpp cg_energy_table_linear_bondcorr.o
cg_ensemble.o: cg_ensemble.fpp cg_enefunc_str_mod.mod cg_ensemble_str_mod.mod cg_dynamics_str_mod.mod 
cg_ensemble_mod.mod: cg_ensemble.fpp cg_ensemble.o
cg_ensemble_str.o: cg_ensemble_str.fpp  
cg_ensemble_str_mod.mod: cg_ensemble_str.fpp cg_ensemble_str.o
cg_input.o: cg_input.fpp  
cg_input_mod.mod: cg_input.fpp cg_input.o
cg_md_leapfrog.o: cg_md_leapfrog.fpp cg_output_mod.mod cg_domain_str_mod.mod cg_enefunc_str_mod.mod cg_dynvars_mod.mod cg_assign_velocity_mod.mod cg_output_str_mod.mod cg_domain_mod.mod cg_update_domain_mod.mod cg_energy_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_ensemble_str_mod.mod cg_dynvars_str_mod.mod cg_pairlist_str_mod.mod cg_dynamics_str_mod.mod 
cg_md_leapfrog_mod.mod: cg_md_leapfrog.fpp cg_md_leapfrog.o
cg_md_mts.o: cg_md_mts.fpp cg_enefunc_str_mod.mod cg_dynamics_str_mod.mod cg_output_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_assign_velocity_mod.mod cg_domain_str_mod.mod cg_output_str_mod.mod cg_ensemble_str_mod.mod cg_dynvars_str_mod.mod cg_update_domain_mod.mod cg_pairlist_str_mod.mod cg_dynvars_mod.mod cg_energy_mod.mod 
cg_md_mts_mod.mod: cg_md_mts.fpp cg_md_mts.o
cg_md_respa.o: cg_md_respa.fpp cg_enefunc_str_mod.mod cg_dynamics_str_mod.mod cg_output_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_assign_velocity_mod.mod cg_domain_str_mod.mod cg_output_str_mod.mod cg_ensemble_str_mod.mod cg_dynvars_str_mod.mod cg_update_domain_mod.mod cg_pairlist_str_mod.mod cg_dynvars_mod.mod cg_energy_mod.mod 
cg_md_respa_mod.mod: cg_md_respa.fpp cg_md_respa.o
cg_md_vverlet.o: cg_md_vverlet.fpp cg_enefunc_str_mod.mod cg_dynamics_str_mod.mod cg_output_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_assign_velocity_mod.mod cg_domain_str_mod.mod cg_output_str_mod.mod cg_ensemble_str_mod.mod cg_dynvars_str_mod.mod cg_update_domain_mod.mod cg_pairlist_str_mod.mod cg_dynvars_mod.mod cg_energy_mod.mod 
cg_md_vverlet_mod.mod: cg_md_vverlet.fpp cg_md_vverlet.o
cg_migration.o: cg_migration.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod cg_boundary_str_mod.mod 
cg_migration_mod.mod: cg_migration.fpp cg_migration.o
cg_minimize.o: cg_minimize.fpp cg_enefunc_str_mod.mod cg_output_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_domain_str_mod.mod cg_output_str_mod.mod cg_minimize_str_mod.mod cg_dynvars_str_mod.mod cg_update_domain_mod.mod cg_pairlist_str_mod.mod cg_dynvars_mod.mod cg_energy_mod.mod 
cg_minimize_mod.mod: cg_minimize.fpp cg_minimize.o
cg_minimize_str.o: cg_minimize_str.fpp  
cg_minimize_str_mod.mod: cg_minimize_str.fpp cg_minimize_str.o
cg_output.o: cg_output.fpp cg_domain_str_mod.mod cg_enefunc_str_mod.mod cg_minimize_str_mod.mod cg_dynvars_mod.mod cg_output_str_mod.mod cg_rpath_str_mod.mod cg_remd_str_mod.mod cg_boundary_str_mod.mod cg_ensemble_str_mod.mod cg_dynvars_str_mod.mod cg_dynamics_str_mod.mod 
cg_output_mod.mod: cg_output.fpp cg_output.o
cg_output_str.o: cg_output_str.fpp  
cg_output_str_mod.mod: cg_output_str.fpp cg_output_str.o
cg_pairlist.o: cg_pairlist.fpp cg_enefunc_str_mod.mod cg_domain_str_mod.mod cg_boundary_str_mod.mod cg_energy_str_mod.mod cg_pairlist_str_mod.mod 
cg_pairlist_mod.mod: cg_pairlist.fpp cg_pairlist.o
cg_pairlist_str.o: cg_pairlist_str.fpp cg_domain_str_mod.mod 
cg_pairlist_str_mod.mod: cg_pairlist_str.fpp cg_pairlist_str.o
cg_remd.o: cg_remd.fpp cg_energy_restraints_mod.mod cg_domain_str_mod.mod cg_energy_str_mod.mod cg_dynvars_str_mod.mod cg_output_mod.mod cg_md_leapfrog_mod.mod cg_restraints_str_mod.mod cg_enefunc_str_mod.mod cg_pairlist_mod.mod cg_enefunc_restraints_mod.mod cg_dynvars_mod.mod cg_md_vverlet_mod.mod cg_boundary_mod.mod cg_output_str_mod.mod cg_remd_str_mod.mod cg_energy_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_ensemble_str_mod.mod cg_pairlist_str_mod.mod cg_dynamics_str_mod.mod 
cg_remd_mod.mod: cg_remd.fpp cg_remd.o
cg_remd_str.o: cg_remd_str.fpp  
cg_remd_str_mod.mod: cg_remd_str.fpp cg_remd_str.o
cg_restart.o: cg_restart.fpp cg_dynvars_str_mod.mod cg_dynamics_str_mod.mod 
cg_restart_mod.mod: cg_restart.fpp cg_restart.o
cg_restraints.o: cg_restraints.fpp cg_restraints_str_mod.mod 
cg_restraints_mod.mod: cg_restraints.fpp cg_restraints.o
cg_restraints_str.o: cg_restraints_str.fpp  
cg_restraints_str_mod.mod: cg_restraints_str.fpp cg_restraints_str.o
cg_rpath.o: cg_rpath.fpp cg_energy_restraints_mod.mod cg_domain_str_mod.mod cg_energy_str_mod.mod cg_output_mod.mod cg_md_leapfrog_mod.mod cg_restraints_str_mod.mod cg_enefunc_str_mod.mod cg_pairlist_mod.mod cg_enefunc_restraints_mod.mod cg_dynvars_mod.mod cg_md_vverlet_mod.mod cg_boundary_mod.mod cg_output_str_mod.mod cg_rpath_str_mod.mod cg_energy_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_ensemble_str_mod.mod cg_dynvars_str_mod.mod cg_pairlist_str_mod.mod cg_dynamics_str_mod.mod 
cg_rpath_mod.mod: cg_rpath.fpp cg_rpath.o
cg_rpath_str.o: cg_rpath_str.fpp cg_output_str_mod.mod 
cg_rpath_str_mod.mod: cg_rpath_str.fpp cg_rpath_str.o
cg_setup_cgdyn.o: cg_setup_cgdyn.fpp cg_input_mod.mod cg_output_mod.mod cg_domain_str_mod.mod cg_energy_str_mod.mod cg_rpath_str_mod.mod cg_restraints_str_mod.mod cg_control_mod.mod cg_enefunc_str_mod.mod cg_ensemble_mod.mod cg_pairlist_mod.mod cg_minimize_str_mod.mod cg_minimize_mod.mod cg_remd_mod.mod cg_dynvars_mod.mod cg_boundary_mod.mod cg_dynamics_mod.mod cg_output_str_mod.mod cg_rpath_mod.mod cg_domain_mod.mod cg_remd_str_mod.mod cg_energy_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_enefunc_mod.mod cg_boundary_str_mod.mod cg_ensemble_str_mod.mod cg_restart_mod.mod cg_dynvars_str_mod.mod cg_enefunc_fit_mod.mod cg_pairlist_str_mod.mod cg_dynamics_str_mod.mod cg_restraints_mod.mod 
cg_setup_cgdyn_mod.mod: cg_setup_cgdyn.fpp cg_setup_cgdyn.o
cg_setup_mpi.o: cg_setup_mpi.fpp cg_energy_mod.mod cg_remd_mod.mod cg_rpath_mod.mod cg_energy_str_mod.mod 
cg_setup_mpi_mod.mod: cg_setup_mpi.fpp cg_setup_mpi.o
cg_update_domain.o: cg_update_domain.fpp cg_enefunc_str_mod.mod cg_enefunc_mod.mod cg_communicate_str_mod.mod cg_communicate_mod.mod cg_boundary_str_mod.mod cg_migration_mod.mod cg_domain_str_mod.mod cg_pairlist_mod.mod cg_minimize_str_mod.mod cg_domain_mod.mod cg_pairlist_str_mod.mod cg_dynamics_str_mod.mod 
cg_update_domain_mod.mod: cg_update_domain.fpp cg_update_domain.o
